# 数据帧格式定义
length: 64                #帧长度（包括头尾）stm32发来的数据包含时间戳则帧长度为 72
frame:
  header: [0x51, 0x51]     # 2字节帧头
  footer: [0x0D, 0x0A]     # 2字节帧尾
  payload_fields:           # 有效载荷字段定义
    # Motor_1:
    #   angle: int32_t
    #   speed: int32_t
    #   current: int32_t
    # Motor_2:
    #   angle: int32_t
    #   speed: int32_t
    #   current: int32_t
    # Motor_3:
    #   angle: int32_t
    #   speed: int32_t
    #   current: int32_t
    # Motor_4:
    #   angle: int32_t
    #   speed: int32_t
    #   current: int32_t
    # Adsorb_1: int32_t
    # Adsorb_2: int32_t
    # Adsorb_3: int32_t
    # Sec_f: uint64_t
    - name: Motor_1
      fields:
      - { name: angle,   type: int32_t }
      - { name: speed,   type: int32_t }
      - { name: current, type: int32_t }
    - name: Motor_2
      fields:
      - { name: angle,   type: int32_t }
      - { name: speed,   type: int32_t }
      - { name: current, type: int32_t }
    - name: Motor_3
      fields:
      - { name: angle,   type: int32_t }
      - { name: speed,   type: int32_t }
      - { name: current, type: int32_t }
    - name: Motor_4
      fields:
      - { name: angle,   type: int32_t }
      - { name: speed,   type: int32_t }
      - { name: current, type: int32_t }
    - { name: Adsorb_1, type: int32_t }
    - { name: Adsorb_2, type: int32_t }
    - { name: Adsorb_3, type: int32_t }
